spring:
  application:
    name: boa-leitura
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5001/boa-leitura
    username: user
    password: password
  jpa:
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

restClient:
  openLibrary:
    baseUrl: https://openlibrary.org/api/
  googleApi:
    baseUrl: https://www.googleapis.com/

jobrunr:
  background-job-server:
    enabled: true
    poll-interval-in-seconds: 15
    worker-count: 4
  dashboard:
    enabled: false
  job-scheduler:
    enabled: true
  database:
    skip-create: true
  jobs:
    default-number-of-retries: 5
    metrics:
      enabled: true

server:
  port: 1980